"""Aktualizacia stav funkcie a logiky pre BIZTRIP

Revision ID: 1d9a35ca5656
Revises: 
Create Date: 2025-06-27 08:56:50.326088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9a35ca5656'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.alter_column('meno',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('priezvisko',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('spolucestujuci',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('odkial',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('kam',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('od_datum',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('do_datum',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('miesto',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.alter_column('miesto',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('do_datum',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('od_datum',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('kam',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('odkial',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('spolucestujuci',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('priezvisko',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('meno',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
